services:
  # Backend service
  - type: web
    name: linear-regression-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
    buildFilter:
      paths:
        - server/**
        - cpp/**
        - render.yaml
    autoDeploy: true

  # Frontend service (static site)
  - type: web
    name: linear-regression-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        fromService:
          name: linear-regression-api
          type: web
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    buildFilter:
      paths:
        - client/**
        - render.yaml 